trainingInput:
  scaleTier: CUSTOM
  masterType: complex_model_l_gpu
  workerType: complex_model_l_gpu
#  hyperparameters:
#    goal: MAXIMIZE
#    hyperparameterMetricTag: accuracy
#    maxTrials: 10
#    maxParallelTrials: 4
#    params:
#      - parameterName: learning_rate
#        type: DOUBLE
#        minValue: 0.0001
#        maxValue: 0.01
#        scaleType: UNIT_REVERSE_LOG_SCALE
#      - parameterName: model_level
#        type: INTEGER
#        minValue: 1
#        maxValue: 3
#      - parameterName: n_mfcc
#        type: DISCRETE
#        discreteValues: [10, 20, 40]
#      - parameterName: audio_duration
#        type: DISCRETE
#        discreteValues: [1, 2, 4, 6]